---
- name: Create Linux OS report for consumption in a container
  hosts: all
  gather_facts: false
  tasks:
    - name: Podman is installed
      yum:
        name: '@container-tools'
        state: present
      when: "'container_hosts' in group_names"

    - name: OS Report directory is present
      file:
        path: "{{ ansible_env.HOME }}/os-report"
        state: directory