---
- name: Create the Ansible service account on target hosts
  hosts: all
  tasks:
    - name: svcansible user is present
      user:
        name: svcansible
        home: /var/lib/svcansible
        comment: Service account for Ansible
        state: present
        system: True

    - name: .ssh directory is present in svcansible home and has the correct permissions
      file:
        path: /var/lib/svcansible/.ssh
        state: directory
        owner: svcansible
        group: svcansible

    - name: authorized_keys is present and has the correct permissions
      ansible.posix.authorized_key:
        user: svcansible
        state: present
        key: "{{ svcansible_public_key }}"

    - name: svcansible is included in sudoers.d
      copy:
        dest: /etc/sudoers.d/svcansible
        content: "svcansible ALL=(ALL) NOPASSWD: ALL\n"
        owner: root
        group: root
        mode: 'ug+rwX,o='