---
- name: Generate the OS report for container-based consumption
  hosts: all
  gather_facts: true
  tasks:
    - name: 'Preflight Varible check :: home_dir'
      fail: msg='Please include the home_dir to the variable "home_dir"'
      run_once: true
      when: 'home_dir is not defined'
    - name: 'Preflight Varible check :: container_host'
      fail: msg='Please include the container_host to the variable "container_host"'
      run_once: true
      when: 'container_host is not defined'
    - name: 'Preflight Varible check :: target_port'
      fail: msg='Please include the target_port to the variable "target_port"'
      run_once: true
      when: 'target_port is not defined'
    - name: 'Slack Token present check slack alert variables'
      block:
      - name: 'Preflight Varible check :: channel'
        fail: msg='Please include the channel to the variable "channel"'
        run_once: true
        when: 'channel is not defined'
      - name: 'Preflight Varible check :: slackuser'
        fail: msg='Please include the slackuser to the variable "slackuser"'
        run_once: true
        when: 'slackuser is not defined'
      when: 'slack_token is defined'


    - name: Create the OS report and limit it to the container host
      block:
      - name: OS Report directory is present
        file:
          path: "{{ home_dir }}/os-report/css"
          state: directory

      - name: CSS is present on remote host
        copy:
          src: CSS/main.css
          dest: "{{ home_dir }}/os-report/css/main.css"

      - name: HTML report is created
        template:
          src: report-osversion.j2
          dest: "{{ home_dir }}/os-report/index.html"

      - name: OS Report container is launched
        containers.podman.podman_container:
          name: os-report
          image: quay.io/samander/convert2rhel-os-dashboard:latest
          state: started
          volume:
            - "{{ home_dir }}/os-report:/var/report:Z"
          ports:
            - "{{ target_port }}:8080"
      - name: Sending URL link to Slack for Reports
        slack:
         token: "{{ slack_token }}"
         msg: 'OS Inventory Report generated at http://{{container_host}}:{{target_port}}'
         channel: "{{ channel }}"
         username: "{{ slackuser }}"
        run_once: true
        delegate_to: localhost
        when: 'slack_token is defined'
      run_once: True
      delegate_to: "{{ container_host }}"
