---
- name: Generate the OS report for container-based consumption
  hosts: all
  gather_facts: true
  tasks:
    - name: Local container config directories exist
      file:
        path: "{{ home_dir }}/.local/share/containers"
        state: directory
        
    - name: registries.conf is present 
      copy:
        dest: "{{ home_dir }}/.local/share/containers/registries.conf"
        content: -<
          [registries.search]
          registries = ['quay.io, 'docker.io']
      when: "'container_hosts' in group_names"

    - name: OS Report directory is present
      file:
        path: "{{ home_dir }}/os-report"
        state: directory
      when: "'container_hosts' in group_names"

    - name: HTML report is created
      template:
        src: report-osversion.j2
        dest: "{{ home_dir }}/os-report/index.html"
      when: "'container_hosts' in group_names"

    - name: OS Report container is launched
      containers.podman.podman_container:
        name: os-report
        image: quay.io/samander/convert2rhel-os-report:latest
        state: started
        volume:
          - "{{ home_dir }}/os-report:/var/os-report"
        expose:
          - 8080
      when: "'container_hosts' in group_names"
