---
- name: Generate the OS report for container-based consumption
  hosts: all
  gather_facts: true
  tasks:
    - name: OS Report directory is present
      file:
        path: "{{ home_dir }}/os-report"
        state: directory
      when: "'container_hosts' in group_names"

    - name: HTML report is created
      template:
        src: report-osversion.j2
        dest: "{{ home_dir }}/os-report/index.html"
      when: "'container_hosts' in group_names"

    - name: OS Report container is launched
      containers.podman.podman_container:
        name: os-report
        image: quay.io/samander/convert2rhel-os-report:latest
        state: started
        volume:
          - "{{ home_dir }}/os-report:/var/os-report"
        expose:
          - 8080
      when: 1 == 2
