---
- name: Install podman on the target host
  hosts: all
  gather_facts: false
  tasks:
    - name: Install podman on {{ container_host }}
      block:
      - name: Podman is installed
        yum:
          name: '@container-tools'
          state: present

      - name: Port {{ target_port }} is exposed
        firewalld:
          port: "{{ target_port }}/tcp"
          state: enabled
          immediate: yes

      run_once: True
      delegate_to: "{{ container_host }}"
