---
- name: Cleanup the containerized OS Report
  hosts: all
  gather_facts: False
  tasks:
    - include: preflight-checks-os-report.yml
    
    - name: Cleanup container config
      block:
      - name: Stop the OS Report container
        containers.podman.podman_container:
          name: os-report
          state: absent
      
      - name: The os-report directory is removed
        file:
          path: "{{ home_dir }}/os-report"
          state: absent
      run_once: True
      delegate_to: "{{ container_host }}"