---
- name: Generate the OS report for container-based consumption
  hosts: all
  gather_facts: true
  tasks:
    - include: preflight-checks-os-report.yml

    - name: Create the OS report and limit it to the container host
      block:
      - name: OS Report directory is present
        file:
          path: "{{ home_dir }}/os-report/css"
          state: directory

      - name: CSS is present on remote host
        copy:
          src: CSS/main.css
          dest: "{{ home_dir }}/os-report/css/main.css"

      - name: HTML report is created
        template:
          src: report-osversion.j2
          dest: "{{ home_dir }}/os-report/index.html"

      - name: OS Report container is launched
        containers.podman.podman_container:
          name: os-report
          image: quay.io/samander/convert2rhel-os-dashboard:latest
          state: started
          volume:
            - "{{ home_dir }}/os-report:/var/report:Z"
          ports:
            - "{{ target_port }}:8080"
            
      - name: Sending URL link to Slack for Reports
        slack:
         token: "{{ slack_token }}"
         msg: 'OS Inventory Report generated at http://{{container_host}}:{{target_port}}'
         channel: "{{ channel }}"
         username: "{{ slackuser }}"
        run_once: true
        delegate_to: localhost
        when: 'slack_token is defined'
      run_once: True
      delegate_to: "{{ container_host }}"
