---
- name: Finish the conversion to RHEL
  hosts: all
  tasks:
    - name: Execute the Convert2RHEL script
      shell: convert2rhel -k "{{ activation_key }}" -o "{{ satellite_organization }}" --debug -y
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'OracleLinux'
      notify: Reboot the remote host

    - name: Refresh host facts
      setup:

    - name: Validate the host is now running RHEL
      fail:
        msg: "Remote host is still running {{ ansible_distribution }}"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'OracleLinux'

    - include: register-insights.yml
      when: register_to_insights == 'true'

  handlers:
    - name: Reboot the remote host
      reboot: