---
- name: Setup Convert2RHEL
  hosts: all
  tasks:
    - include: convert2rhel_repo_local.yml
      when: use_local_convert2rhel

    - include: convert2rhel_repo_remote.yml
      when: convert2rhel_source == 'remote'