---
- name: Playbook to undo changes made before running 'convert2rhel'
  hosts: all
  tasks:
    - include: preflight_checks.yml
    
    - name: Service account is removed
      user:
        name: "{{ svcansible_username }}"
        state: absent 
      when: use_svcansible == 'True'

    - name: Service account home directory is deleted
      file:
        path: "{{ svcansible_home }}/{{ svcansible_username }}"
        state: absent
      when: use_svcansible == 'True'

    - name: Service account is not in /etc/sudoers.d
      file:
        path: "/etc/sudoers.d/{{ svcansible_username }}"
        state: absent
      when: use_svcansible == 'True'

    - name: Convert2RHEL is not present on the remote host
      yum:
        name: 'convert2rhel'
        state: absent

    # Make sure to add section later for removing Katello RPM for local installs
    - name: The Convert2RHEL repo is not present
      yum_repository:
        name: convert2rhel
        state: absent
      when: convert2rhel_source == 'remote'

    - name: The Red Hat GPG key is deleted
      file:
        path: "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
        state: absent
      when: convert2rhel_source == 'remote'

    - name: The Convert2RHEL directory is absent
      file:
        path: "/usr/share/convert2rhel"
        state: absent
      when: convert2rhel_source == 'remote'

    - name: The system is unregistered from Satellite
      shell: "subscription-manager unregister"
      when: convert2rhel_source == 'local'
      ignore_errors: yes

    # Note that this does not automatically remove Subscription Manager if it was installed
    - name: Satellite CA package is uninstalled
      yum:
        name: "katello-ca-consumer-*"
        state: absent
      when: convert2rhel_source == 'local'

    - name: Subscription Manager is Uninstalled (6)
      yum:
        name:
          - subscription-manager
          - python-rhsm
        state: absent
      when:
        - rhel6_rhsm_preinstalled == 'False'
        - ansible_distribution_version == '6.10'

    - name: The RHSM repo is not present
      yum_repository:
        name: rhsm-repo
        state: absent
      when:
        - rhel6_rhsm_preinstalled == 'False'
        - ansible_distribution_version == '6.10'