---
- name: Connect to Ansible Tower API
  hosts: all
  gather_facts: False
  tasks:
    - name: Authenticate to Ansible Tower API
      uri:
        url: "{{ lookup('env', 'TOWER_HOST') }}/api/v1/authtoken/"
        method: POST
        body: {"username": "{{ lookup('env', 'TOWER_USERNAME') }}", "password": "{{ lookup('env', 'TOWER_PASSWORD') }}"}
      register: tower_token
    
    - name: Print out token
      debug:
        var: tower_token
