---
- block:
    - name: determine hosts that are up
      wait_for_connection:
        timeout: 5
      vars:
        ansible_connection: ssh

    - name: add devices with connectivity to the "running_hosts" group
      group_by:
        key: "running_hosts"
  rescue:
    - debug: msg="Cannot connect to {{ inventory_hostname }}"
