---
- name: 'Preflight Varible check :: home_dir'
  fail: msg='Please include the home_dir to the variable "home_dir"'
  run_once: true
  when: 'home_dir is not defined'

- name: 'Preflight Varible check :: container_host'
  fail: msg='Please include the container_host to the variable "container_host"'
  run_once: true
  when: 'container_host is not defined'

- name: 'Preflight Varible check :: report_user'
  fail: msg='Please include the report_user to the variable "report_user"'
  run_once: true
  when: 'report_user is not defined'
