---
    - include: preflight-checks.yml

    - name: Install podman on {{ container_host }}
      block:
      - name: Podman is installed on {{ container_host }}
        yum:
          name: '@container-tools'
          state: present

      - name: Port {{ target_port }} is exposed
        firewalld:
          port: "{{ target_port }}/tcp"
          state: enabled
          immediate: yes
      ignore_errors: yes
      run_once: True
      delegate_to: "{{ container_host }}"
