---
    - include: preflight-checks.yml

    - name: Sending URL link to Slack for Reports
      remote_user: "{{ report_user }}"
      community.general.slack:
        token: "{{ slack_token }}"
        msg: 'Container Report generated at http://{{container_host}}:{{target_port}}'
        channel: "{{ channel }}"
        username: "{{ slackuser }}"
      run_once: true
      delegate_to: "{{ container_host }}"
      when: 'slack_token is defined'
